### ISSUE TITLE
Allow a Space to be provisioned without the registry

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#10]
Octopus currently requires the registry so that it can map Instance names to config file locations. Should we add the ability to specify the config file location directly instead?

**Comment by droyad** [comment]
If we overload the `--Instance` option to take a fully qualified path, we could detect that and skip reading the registry for the config file location. We should specify that path directly in the service as well.

This would however mean that the Manager does not recognise that install, which would be ok as ODCM would be managing it directly.

The upside is that it would simply the installation of a space.

Downside may be that manual command line management is more difficult.

This would also help if/when we go to Linux.

**Comment by matt-richardson** [comment]
Would also mean that the `list-instances` command wouldn't find it.

I do like the idea of overloading the `--instance` option though. That would be useful in other scenarios.

As per https://github.com/OctopusDeploy/Specs/issues/8#issuecomment-302269510, I'm not sure this is necessary though.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
