### ISSUE TITLE
List of available Octopus Deploy versions for ODCM

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#11]
How will ODCM know about and retrieve ODCM and OctopusDeploy installs

**Comment by droyad** [comment]
## NuGet Feed
We or the customer maintains a NuGet feed of Octopus packages

**Comment by droyad** [comment]
## Octofront
We publish OD packages via Octofront and ODCM can query the Octofront API to retrieve available packages. This has the advantage that we would add extra metadata, for example:
- Flagging a release as bad, prompting the ODCM admin (or auto) to update/downgrade
- Having "rings", let some customers delay install until we mark a release as "good"

**Comment by droyad** [comment]
## Fileshare
For customers whose ODCM does not have internet access they can download the package from our website/feed and put it on a file share

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
