### ISSUE TITLE
ODCM to Space communications

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#12]
- ODCM needs to talk to Spaces (eg collect statistics, sync users)
- Spaces need to talk to ODCM (eg licence checks)
- Spaces may also need to talk to each other (eg variable sharing)

**Comment by droyad** [comment]
Initially I think we should require unrestricted access from a space back to at least one ODCM node. In the future, we could allow proxying through an agent (see #9) for restricted networks.

**Comment by droyad** [comment]
## Via the API
ODCM and Spaces would know each other's addresses and could connect to each other's APIs and authenticate using shared certificates. 

The downside is that this would require the firewall to open connections in both directions. This is perhaps not a big stretch though as both the Space and ODCM need their APIs accessible in order to function. The communication would also be request-response, which may be sufficient.

We could run into a problem though in restricted environments (eg PCI) that only allow outgoing connections, but a ODCM instance running inside that environment should resolve that (it only makes outgoing connections to the DB).

**Comment by droyad** [comment]
## Halibut Backchannel

ODCM and Spaces would connect to each other in the same way OD Server and tentacles do, via Halibut. The advantage is we can have a rich RPC style interaction.

This would allow full duplex conversations, but Halibut still proscribes a Server-Client relationship, whereby the client issues requests and the server responds. (ODCM would be generally be the client, ie, the issuer of commands). However if the Space needs something from ODCM, it would need to play the role of the client. This would probably need a connection going the other way, resulting in mirrored halibut connections. Again this results in the firewall requiring connections in both directions.

A big downside is if polling connections are required. Those connections need to be kept open in order to work, whereas listening connections are opened on demand. This could result in a N+1 problem if spaces connect directly with each other.

**Comment by droyad** [comment]
On the whole two way communication, I haven't thought through when it is needs. Perhaps if we implement some restrictions it would make it a lot simpler:

- Space to Space features are only possible if there the initiator can establish the connection to the other Space.
- Each space needs to be able to establish a connection to at least one ODCM node, and vise versa 
- We could assign spaces and ODCM nodes to network segments, and assign tasks accordingly

**Comment by droyad** [comment]
Do we want to expose all of our ODCM/Space communications via the public API?

**Comment by droyad** [comment]
Bi-directional certificate authentication is nice (for API or Halibut-over-WebSockets), but SSL certificate rotation could be problematic as the trusts would need to be updated. ODCM might have to manage it.

**Comment by matt-richardson** [comment]
I'm currently working on certificate rotation for OD + Tentacle... That could be useful.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
