### ISSUE TITLE
Support for Username/Password authentication with Spaces

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#13]
Should ODCM and Spaces support Username/Password as an authentication method

**Comment by droyad** [comment]
I don't think we should support this. It adds complexity, particularly when it comes to fending off brute force attacks.

Organisations the will use ODCM should already have some sort of Auth mechanism inplace, be it AD, AAD, LDAP or some other OAuth implementation.

A common use case for Username/password is to allow access from outside the organisation. We could provide guidance on how to set up something like Auth0 (which supports username/password as an OAuth provider).

**Comment by PaulStovell** [comment]
Not relevant as ODCM is dead
