### ISSUE TITLE
Users and identity management

### ISSUE THREAD

**Issue by slewis74** [OctopusDeploy/Specs#17]
In 3.5 we introduced the ability to enable multiple authentication providers.  ODCM will support this same idea.

To retain backward compatibility at the time we did not change the user table and data structures.  An updated structure that better supports the multi provider model should be included in ODCM.

A User 1->* Identity model is what we're suggesting for ODCM.

User has Username, IsActive, IsService and ApiKey.
Identity has Name (aka Display Name) and Email Address.

This lets us correctly model the data coming from AD, Azure AD etc and will allow mapping of multiple external identities to a single user more correctly/easily.

Updating Octopus to use this structure would allow better integration and allow us to fix some current issues even when ODCM isn't being used.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.

**Comment by slewis74** [comment]
Yep, this was all covered in the identity changes made in 3.17
