### ISSUE TITLE
Execute jar file using command line or shell script from Octopus Deploy

### ISSUE THREAD

**Issue by vivekaundkar** [OctopusDeploy/Specs#20]
I have a jar file which can be executed as a command line to talk to IBM RQM tool.
On my local machine I am able to execute this jar and get required task done.
Now I want to set it up on Octopus.
Does Octopus have any built in support for jar execution?
If no can someone help with steps on how can I achieve my goal of execution jar file from octopus deploy?

**Comment by droyad** [comment]
Hi @vivekaundkar, please contact us via our support channels (https://octopus.com/support). This repository is for the discussion of upcomming features.
