### ISSUE TITLE
On-demand Provisioning of Task Runners and Workers

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#31]
[Overall Design](https://github.com/OctopusDeploy/Specs/issues/21#issuecomment-346232071)

We want to allow Octopus to on-demand provision Task Runners and Workers to achieve scalability, ie lots of things while turning them off when not needed.

## Design points
- What should we support out of the box (AWS, Azure, Kuberneties, ???)
- What component(s) do the provisioning?
- Are there things in the roadmap that will help us do this

**Comment by droyad** [comment]
Does this need to wait for the Resources and Infrastructure features?

We could just support API endpoint (eg Lambda) or Script (Bash/Powershell) and allow customers to write their own provisioning logic

**Comment by droyad** [comment]
I see the Lead Scheduler as being the one to provision Task Runners. Task Runners would then provision workers as needed.

We should also be able to set limits:
- min and max instances
- idle period
- number of deployments

**Comment by distantcam** [comment]
What runs the task, the Task Runner or the Worker?

If the Worker is running the task, do the Task Runners need to scale dynamically?

**Comment by droyad** [comment]
The Task Runner runs the taks. The Worker only runs single scripts (ie just executes Calamari).
