### ISSUE TITLE
Discussion/ODCM: Metrics format

### ISSUE THREAD

**Issue by carlpett** [OctopusDeploy/Specs#4]
The monitoring and reporting part of the RFC only mentions having a dashboard internally in Octopus. I would like to propose exposing the metrics on a format that can also be used to plug this into external monitoring and alerting systems. 

I would suggest using the Prometheus exposition format (https://prometheus.io/docs/instrumenting/exposition_formats/), since it is both a very strong product in itself, and also has bridges available for many other systems (Graphite, StatsD, etc). 

There is a .net client library (https://github.com/andrasm/prometheus-net), so getting it into Octopus should be fairly simple. 

I don't see this as conflicting with having the functionality within Octopus as such, since it provides nicely for teams that do not have their own monitoring infrastructure. But for larger organizations who *do* have such setups, integrating seamlessly would be nice.

**Comment by NickJosevski** [comment]
Thanks for raising this @carlpett. There's always requests for more extensibility points in Octopus. There was also a [mention on twitter](https://twitter.com/BamShanks/status/862445804144836608) of specific services (e.g. DataDog / Nagios) to integrate with would be ideal to let customers decide.

The idea of using a common format would be ideal.

@carlpett if you have time would you care to expand on what you would care about having metrics on, just performance/utilization of a Space? So you can see how it's performing over time? 

We were thinking if the person tasked with administering the Spaces could see them becoming overload over time, reach out to the teams using the Space to see if they need further partitioning. Anything else that would be of value?

**Comment by carlpett** [comment]
Performance and utilization sounds useful, but I think they may need some further definition :) Here are some thoughts, with example output in Prometheus format just to give a feel for how it could look (in the larger space of deployment and automation, Prometheus is becoming quite common, with both Kubernetes and Docker having native support, so therefore the suggestion to use it). The exact labels and types may not be optimal, of course.  

`octopus_tentacle_deployment_step_duration_seconds{space="Team A", project="Foo", step="Deploy package", outcome="success"} 22.2`
Read this as "time taken for a given step/project/space to reach a given outcome". Also note that a consumer of these metrics, such as Prometheus, would add some extra labels, such as `instance`, which would then also let you query this data per node.
Probably this should be a histogram data type, rather than a gauge (see descriptions [here](https://prometheus.io/docs/concepts/metric_types/)) as written above, but that would have made a messy example.
With this data, I would be able to see how often deployments fail, how long they take, and what teams/projects are deploying, with different drill-downs depending on what I'm looking for (most active team, is some node performing worse that others, etc).

`octopus_server_current_deployments{space="Team B", project="Bar"} 3`
Having the number of current deployments in flight would allow the operator to see how usage varies over different times of day, for example, and correlate that with durations. Not sure how many levels of drill-down are relevant here, but possibly add environment as well.

```
octopus_server_cpu_seconds_total 1231234
octopus_server_memory_used_bytes 65124123

octopus_tentacle_cpu_seconds_total 1231234
octopus_tentacle_memory_used_bytes 65124123
```
Having some measure of how much resources the servers and tentacles are using is always nice. This should be restricted to just process-level information, though, not going into server-level monitoring (for Prometheus users there is the [wmi_exporter](https://github.com/martinlindhe/wmi_exporter), and other monitoring systems each have their own solutions).

```
octopus_server_spaces 5
octopus_server_projects{space="Team C"} 8
octopus_server_users{space="Team A"} 12
octopus_server_releases_total{space="Team B", project="Baz"} 58
octopus_server_deployments_total{space="Team A", project="Qux", environment="Test"} 1213
```
Some basic metadata about the how the teams are using Octopus. We've built a dashboard showing team release frequency internally by having an Octopus step which posts some deployment metadata into Prometheus, which anyone could do with this.

---

These were just a few off the top of my head, I'm sure there are quite a few more that would be interesting that will come up as this is explored. Note that I split the metrics into Server and Tentacle, I would envision that the tentacles expose their metrics independently from the server. For the built-in dashboards, the server could collect these metrics from the tentacles itself, but external monitoring systems should be able to get it directly from the source, so to speak.

This became quite the wall of text... Hope it is a bit useful, and I'm very happy to discuss this more!

**Comment by matt-richardson** [comment]
I was pondering metrics the other day, and I think it'd be a win if we implemented something like [Metrics.Net](https://github.com/Recognos/Metrics.NET) to track metrics within OD. 

Prometheus has also come onto my radar - definitely something we should look into more.

Combining the 2, looks like there's [a plugin](https://github.com/DEXSinc/Metrics.NET.Prometheus) that has potential.

**Comment by brentm5** [comment]
I agree that visibility into the health of Octopus Deploy instances is something that is currently missing.  I know I recently posted a user voice a little while ago which was slightly opinionated for our setup but something more generic would be awesome.  We currently have some random stats about active tasks, environments, and machines so that we can get some visility into our performance metrics.  We still have 0 clue about certain aspects internally like connection pools and whatnot which would be really helpful.  I think in addition to that being able to break down different deployments to understand benchmarks would be helpful for alerting.  

[User Voice Post](https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/19114147-push-octopus-deploy-performace-data-to-statsd)

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.

**Comment by carlpett** [comment]
@PaulStovell Even though ODCM isn't relevant, I think having metrics for the server instance would be very valuable. But perhaps that could/should go in a separate issue?

**Comment by facundofarias** [comment]
+1
Any news in here?

**Comment by NickJosevski** [comment]
There's a feature coming in the next 1-2 months called Spaces. There'll be some blog posts coming out soon. 

In the mean time the most recent info on Spaces:
 * https://www.youtube.com/watch?v=tgmjnxU4ZOA
 * https://octopus.com/blog/octopus-spaces-blog-series-kick-off
