### ISSUE TITLE
Composite Step Templates - Allow setting conditions

### ISSUE THREAD

**Issue by markgould** [OctopusDeploy/Specs#43]
Not sure if this is planned for Composite Step Templates or not, but it would be great to be able to set conditions for the steps. 

For example, I have steps A,B,C right now. A and C need to execute if the tenant is tagged with 'Azure', B runs always. It would be nice to declare this somehow on the template or in the project when it is added.

**Comment by zentron** [comment]
@markgould yep it is expected that the conditions for CST will be exposed through to the consuming project where appropriate (e.g. environments etc) and variable conditions available to be set on the step itself.
