### ISSUE TITLE
ODCM - OD Migration Mechanism and the User Story

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Specs#5]
# Migrations in ODCM

## Phasing out 'Migrator.exe'

We have a long-term goal of removing support for (deprecating) `Migrator.exe`, in favour of the new release promotions work that is currently underway.

However we need Migrator for ODCM, to help customers migrate from larger Spaces (lots of projects) into smaller, more manageable Spaces. So we're planning on creating new commands in the Migrator project to help with Spaces, and deprecating the current `import`, `export` and `partial-export` commands.

## Pre-conditions

- ODCM will include a Task/TaskRunner system similar to OD, so the Migrations UI will simply hand this migration work off to a task
- The task will sit in `Executing` while the various export/import operations happen between the Spaces
- The Spaces will make callbacks to ODCM to let it know what stage of the migration it is up to (eg. SpaceA has now finished export)
- ODCM will include a `Migration` table to help us keep track of where a migration task is currently up to, which will help ODCM orchestrate the export against SpaceA, then know when to begin the import operation on SpaceB
- `Migrator.exe` is currently bundled with `Octopus.Server.exe`, so we can presumably call this anywhere an Octopus instance is installed (if not, we'll bundle this like we do with Calamari)

## Version limitations

Migrations can only be performed between instances using the same version. Migrator does not currently enforce this, but we will enforce it when implementing this Spaces migration story.

## Data-flow for an ODCM Migration

Eg. Perform a export migration on SpaceA and import it into SpaceB

ODCM will create a task for a given migration (all data that we feed it from the Migration UI - see mockup below). The task arguments will end up looking something like this:

```
{
	"Source": "Spaces-1",
	"SourceApiKey": "API-1234",
	"Destination": "Spaces-2",
	"Projects": [ "Projects-1", "Projects-2" ],
	"IncludeMachines": false,
	"IncludeSubscriptions": true,
	... etc.
	"DryRunImport": false,
}
```

The ODCM Migrations UI then becomes a one-time trigger for a migration. As soon as you click "Begin Migration", we spawn a task with your selected arguments, and that task takes over orchestration of the migration between the Spaces. Users may then choose to cancel the migration task if they wish by clicking into the task (just like we currently do in OD).

![odcm-migrations-ui](https://cloud.githubusercontent.com/assets/819605/26664182/e9a75ae4-46d2-11e7-9bfa-e47bf018aa46.png)

### ODCM Migration Orchestration

The migration task will:

- Create an entry in the ODCM `Migration` table (this table will include a link to the `ServerTask`), with an enum `MigrationStatus`, which options including:
    - Unknown
    - ExportStarted
    - ExportSucceeded
    - ExportFailed
    - ImportStarted
    - ImportSucceeded
    - ImportFailed
    - Complete
- Make an API call to SpaceA: `/api/migrations/partial-export` with query string args:
    - projects=ProjectA,ProjectsB
    - password=Demo1234
    - successCallbackUri=`http://my-odcm/api/migrations/partial-export-callback?caller=Migrations-123&packageId=migration-4gknq5cx.1.0.0&success=true`
    - failureCallbackUri=`http://my-odcm/api/migrations/partial-export-callback?caller=Migrations-123&success=false`
- Update `Migration.Status` = **ExportStarted**
- Sit in an "Executing" task state, polling the `Migration` table to see when the `Status` property has been updated (this will be updated when we hear back from the `successCallbackUri` or `failureCallbackUri` callbacks)
- If `ExportFailed`:
    - Update `Migration.Status` = **ExportFailed**
    - End task with failure
- If `ExportSucceeded`:
    - Update `Migration.Status` = **ExportSuccessful**
    - Ready to start the import operation against SpaceB
- Make an API call to SpaceB: `/api/migrations/import` with query string args:
    - packageId=migration-4gknq5cx.1.0.0
    - password=Demo1234
    - successCallbackUri=`http://my-odcm/api/migrations/import-callback?caller=Migrations-123&success=true`
    - failureCallbackUri=`http://my-odcm/api/migrations/import-callback?caller=Migrations-123&success=false`
    - sourcePackageFeed=`http://spaceA:8065`
    - sourceApiKey=API-1234
- Update `Migration.Status` = **ImportStarted**
- Sit in an "Executing" task state, polling the `Migration` table to see when the `Status` property has been updated (this will be updated when we hear back from the `successCallbackUri` or `failureCallbackUri` callbacks)
- If `ImportFailed`:
    - Update `Migration.Status` = **ImportFailed**
    - End task with failure
- If `ImportSucceeded`:
    - Update `Migration.Status` = **ImportSuccessful**
    - delete the export package that was created in SpaceA and we're done
    - Update `Migration.Status` = **Complete**

### What each Space API will be responsible for during an ODCM Migration

SpaceA will perform a `space-export` migration as a task (everything is contained in a script `workspace` folder, which is cleared when we're finished). The task will:

- put the instance into maintenance mode
- perform the `space-export` migration in the current workspace folder (using `Migrator.exe` via our script runner)
- zip the export into its built-in package feed
- call the `successCallbackUri` or `failureCallbackUri` callback URI (if supplied) so ODCM knows the export is complete and what the exported packageId is
- take the instance out of maintenance mode

NOTE: these callbacks are optional (this will give us the flexibility to use this migration API within OD itself, independent of ODCM if desired)

SpaceB will perform a `space-import` migration as a task (everything is contained in a script `workspace` folder, which is cleared when we're finished). The task will:

- put the instance into maintenance mode
- get the exported package from SpaceA (using the provided API key)
- unzip the package into the current workspace folder
- perform the `space-import` migration against this package folder in our workspace (using `Migrator.exe` via our script runner)
- call the `successCallbackUri` or `failureCallbackUri` callback URI (if supplied) so ODCM knows the import is complete
- delete the exported package from SpaceA (using the provided API key). We have now finished the migration
- take the instance out of maintenance mode

### What is exported?

This will essentially work the same as the `partial-export` command does currently, except we will allow multiple projects to be specified. Migrator exports all information that it can infer for a given project. The UI will also allow you to "include" other global information that you may want duplicated to your new Space.

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Version you're migrating FROM and TO have to be the SAME, migrator enforces it?](https://trello.com/c/NJRxUY6k/34-version-you-re-migrating-from-and-to-have-to-be-the-same-migrator-enforces-it)

**Comment by thebigmoosey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migration](https://trello.com/c/ZUNAehIx/6-migration)

**Comment by matt-richardson** [comment]
As we'll probably have to have an endpoint on the OD server to download an "export" of a project and all related entities, I wonder if we could integrate this directly into the normal OD interface:

* use case: I'm not using ODCM, but I have multiple instances
* use case: I'm submitting an issue for diagnosis (maybe we could integrate with the diagnostics zip?)
* use case: I'm an Octopus developer who's reproducing an issue and I need to export from a test instance into a local instance for debugging

**Comment by thebigmoosey** [comment]
FYI description and UI has been updated after investigating/prototyping some ideas this week.

**Comment by matt-richardson** [comment]
I wonder if instead of using callbacks, we return a token and then allow someone to query based on that token? That would allow non-web apps to use the export/import functions as well. This would also mean OD has less knowledge of ODCM.

**Comment by thebigmoosey** [comment]
@matt-richardson Not sure I follow. The callbacks are optional, and only for web-based apps that are calling the migration functions via the API (like ODCM) to know when the export or import tasks have completed successfully or not. Non-web apps will still be able to call the export/functions just as migrator works today (ie. not going through the API) if they so choose

I see the benefits of a callback being that we don't put any additional pressure on the individual AD servers involved in the migration (ie. there's no external "thing" polling OD constantly asking: "Are you done yet?") and it also keeps the changes to OD minimal (ie. just an additional migration API that spawns a task and then works with the Migrator.exe) ... so OD won't have to hold any token.

**Comment by zentron** [comment]
I kind of agree with @matt-richardson . Making it more "invoker agnostic" would allow wider usage that we possibly haven't thought of. Seems otherwise inconsistent with other "long-running-requests" like , perform deployment task etc. One could argue that these should also have a callback-completion pattern for consistency (not that I think they necessarily should).  Not yet convinced it needs to be so over-engineered with a new way of interacting.

**Comment by matt-richardson** [comment]
Ahh, I hadn't realised it was just going to spawn `migrator.exe`. If that's still around, its less important. As it was, I wasn't 100% convinced of my own idea, but thought I'd throw it up for consideration.

That said, I don't think it'd need to be a special token. It could just be the task id, couldn't it?

I wonder if its possible/easy/wise to support both models? (kinda like [this model](https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/).)

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
