### ISSUE TITLE
Can we delist a Space?

### ISSUE THREAD

**Issue by NickJosevski** [OctopusDeploy/Specs#7]
Define: Enlist - registering/associating an existing Octopus instance with an ODCM, migrating it's user data and having it now manged by that ODCM. 

## Questions
 - Can we reverse the enlistment of a Space? 
 - What are the impacts of supporting / not supporting this scenario?
 - Can this be solved manually with just migrating/exporting to a new non ODCM instance, if it ever does come up?

If a delist happens, what do we do with:
 - The configuration of having ODCM be the identity provider?
 - Shared variables 
 - Shared server extensions
 - Shared step templates, etc

**Comment by NickJosevski** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can we delist a space, once elisted? Discuss in github issue](https://trello.com/c/C0kv2wmy/33-can-we-delist-a-space-once-elisted-discuss-in-github-issue)

**Comment by droyad** [comment]
I think it is something we can definitely support. Anything that is shared would no longer be available. 

Delisting would consist of deleting all nodes of that space. That would remove the program files and instance registrations. The database would be left over.

The end user would then install OD again in the non-ODCM fashion and re-attach the database. The user would need to setup Auth again and possibly admin user along with the extensions

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
