### ISSUE TITLE
How ODCM will gain access to create, update and remove Spaces

### ISSUE THREAD

**Issue by droyad** [OctopusDeploy/Specs#9]
ODCM will have the ability to deploy new spaces, upgrade existing spaces, and remove spaces. This issue discusses the mechanism that ODCM will use to gain access to the VM to perform this maintenance. The actual install process is out of scope for this issue.

**Comment by droyad** [comment]
I propose we support several different modes:

## Local ODCM
In this mode a ODCM node would be running on the target VM. It would use local PowerShell to perform the installation/upgrade. It would run under the context of the service account.

We will be supporting clustered (HA) ODCM through a shared database. Due to the shared DB, all nodes would need to be upgraded at the same time, unless we took great care with the schema transitions. Once customers get to a large number of VMs (5+?), this could be come unweildly.

## Remote Powershell
Use remote PowerShell administration. It is likely to be enabled for customers of ODCM scale. All the machines should also be on the same domain, skirting the issue OD-Tentacle first solved. This means we don't need to install and maintain a remote agent. We could (possibly) have the ability to run the the script as a different user.

This may supersede the previous method as it is a special case of local powershell

## Agent
An agent running on the machine, most likely a stripped down version of ODCM, or a tentacle like service. It would connect to the ODCM cluster via Halibut, so could work in a polling or listening mode. This would also help in restricted (eg PCI) environments where incomming connections are restricted.
Also see #6

**Comment by droyad** [comment]
In #12 I thought we could partition Spaces and ODCM nodes into network segments. This would influence which ODCM node provisioned and managed a particular space. This might be a nice way of modelling remote spaces for promotions as well.

**Comment by PaulStovell** [comment]
I'm closing this as ODCM is no longer relevant, and I don't think this issue is anymore either. If I'm wrong please re-open.
